---
title: "Untitled"
output: html_document
editor_options: 
  chunk_output_type: console
---

I want to test whether doing APSP before steinerTree can speed up the process


```{r}
library(data.table)
library(dplyr)
library(igraph)
library(InteractomeServices)
library(purrr)
library(ggplot2)
library(stringr)
devtools::load_all()
```

```{r}
solverToTest <- stoneTrees_solvers[1:3]

```

```{r}
PtoExclude <- fread("~/Documents/InternalDiscoveryProjects/covid19/EmpiricalHostVirusPPI/Resources/proteins_to_exclude.tsv")

```

```{r}
searchOptions <- samplingStrategyOptions(includedTaxonomies= 9606, filteredAccession = PtoExclude$Accession)

interactome <- generateWorkbenchFilteredNetwork("ETX Interactome v5.2.0", searchOptions)

undirected <- as.undirected(interactome, mode = "collapse")

simpleUndirected <- simplify(undirected)

simpleUndirectedBiggestComponent <- decompose(simpleUndirected) %>% .[order(map_int(., vcount), decreasing = TRUE)] %>%.[[1]]

interactome <- simpleUndirectedBiggestComponent

```


```{r}

seeds <- fread("~/Documents/Workflows/network_construction/data/Table2Head50.txt")

seedName <- list.files("~/Documents/InternalDiscoveryProjects/covid19/EmpiricalHostVirusPPI/covid19Translatome/Resources/Seeds", pattern = ".txt")

seedSetlist <- map(seedName, ~{ fread(paste0("~/Documents/InternalDiscoveryProjects/covid19/EmpiricalHostVirusPPI/covid19Translatome/Resources/Seeds/", .x)  ) })


names(seedSetlist) <- str_remove(seedName, ".txt")


seedSetlist <- map(seedSetlist, ~{ .x[Accession %in% V(interactome)$name]  })

```


```{r}



steinerTreeBenchDT <-map2(seedSetlist, names(seedSetlist), function(seeds,name){

#seeds <- seedSetlist$TranslatomeCluster1
  
  V(interactome)$isTerminal <- V(interactome)$name %in% seeds$Accession


  Results <- map(solverToTest, ~{

print(.x)

  # Note, The two process are not solving the exact same problem. Stochastic algorithms are a pain

time <- system.time( Solution <- nodeCentricSteinerTreeProblem$new(interactome,
                                                                               solverChoice = .x,
                                                                               verbose = TRUE,
                                                                               solverTrace = 0))#$findSingleSteinerSolution())
#Solution$getNconnectivityConstraintsCalls()
#Solution$getConnectivityConstraints()
#Solution$findSingleSteinerSolution()
#Solution$getNconnectivityConstraintsCalls()
#Solution$getConnectivityConstraints()

save(Solution, file = paste0("./results/etxInteractome_covid19_steinerTreeSolver_",name, "_",.x,".RData"))

  return(data.table(solver = paste(.x),
                    seedSet = paste(name),
                    time = time["elapsed"],
                    vcount = vcount(Solution)))



}) %>% rbindlist()


return(Results)  

  })  %>% rbindlist()


fwrite(steinerTreeBenchDT, paste0("./results/etxInteractome_covid19_steinerTreeSolver.tsv"))

steinerTreeBenchDT
```



```{r}



steinerTreeBenchDT <-map2(seedSetlist, names(seedSetlist), function(seeds,name){

  print(paste("Compute APSP for ", name))
  
  APSPModule <- calculateAPSPmodule(seeds$Accession, interactome)

  V(APSPModule)$isTerminal <- V(APSPModule)$isSeed


  Results <- map(solverToTest, ~{

print(.x)

  # Note, The two process are not solving the exact same problem. Stochastic algorithms are a pain

time <- system.time( Solution <- nodeCentricSteinerTreeProblem$new(APSPModule,
                                                                   solverChoice = .x,
                                                                   verbose = TRUE,
                                                                   solverTrace = 0)$findSingleSteinerSolution())


save(Solution, file = paste0("./results/APSPInteractome_covid19_steinerTreeSolver_",name, "_",.x,".RData"))

  return(data.table(solver = paste(.x),
                    seedSet = paste(name),
                    time = time["elapsed"],
                    vcount = vcount(Solution)))



}) %>% rbindlist()


return(Results)  

  })  %>% rbindlist()

fwrite(steinerTreeBenchDT, paste0("./results/APSPInteractome_covid19_steinerTreeSolver.tsv"))

steinerTreeBenchDT
```


```{r}
ETXinteractomeBenchDT <- rbind(fread(paste0("./results/etxInteractome_covid19_steinerTreeSolver.tsv")) %>% .[,APSPpresolveMethod := FALSE],
                               fread(paste0("./results/APSPInteractome_covid19_steinerTreeSolver.tsv")) %>% .[,APSPpresolveMethod := TRUE])

```
```{r}

ETXinteractomeBenchDT[, .(`TotalTime(hours)` = sum(time)/60/60), by = .(solver, APSPpresolveMethod)] 

ETXinteractomeBenchDT[, .(TotalTime = sum(time)/60/60), by = .(solver)][,TotalTime] %>% sum

ETXinteractomeBenchDT[, .(AvSise = mean(vcount)), by = .(solver, seedSet, APSPpresolveMethod)] 


```

```{r}



presolveMethod.labs <- str_c("APSP presolve method ", c(TRUE, FALSE))
names(presolveMethod.labs) <- c(TRUE, FALSE)

p1 <- ggplot(ETXinteractomeBenchDT, aes(x = solver, y = time/60)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.1, height = 0, aes(color =seedSet)) +
  facet_wrap(~APSPpresolveMethod, labeller = labeller(APSPpresolveMethod = presolveMethod.labs))+
  theme_minimal(base_size = 20) +
  theme(legend.position = "none")+
  labs(y = "Time (min)",
       title = "Time taken to find only one solution")

p2 <- ggplot(ETXinteractomeBenchDT, aes(x = solver, y = time/60)) +
  geom_boxplot(outlier.shape = NA) +
  geom_jitter(width = 0.1, height = 0, aes(color =seedSet)) +
   facet_wrap(~APSPpresolveMethod, labeller = labeller(APSPpresolveMethod = presolveMethod.labs))+
  theme_minimal(base_size = 20) +
  theme(legend.position = "none")+
  scale_y_log10()+
  labs(y = "Time (logScale)",
       title = "Time taken to find only one solution")


#
p3 <- ggplot(ETXinteractomeBenchDT, aes(x = solver, y = vcount))+
  #geom_boxplot() +
   facet_wrap(~APSPpresolveMethod, labeller = labeller(APSPpresolveMethod = presolveMethod.labs))+
  geom_point(aes(color = seedSet)) +
  theme_minimal(base_size = 20) +
  #scale_color_hue()+
  theme(legend.position = "none")+
  labs( y = "number of nodes",
        title = "Size of the solution")




plot <- egg::ggarrange(p1,p2,p3, ncol = 3,
                       
                       top =  paste(
  
  "Steiner tree : collecting 1 solution"))


#ggpubr::ggarrange(p1,p2,p3,p5)


ggsave(plot = plot, filename = "./results/APSPpresolveMethod_SteinerTree.png", width = 25, height = 8)
```

```{r}




allSolutions <- list.files("./results", pattern = "steinerTreeSolver")

allSolutions <- allSolutions[grepl("RData", allSolutions)]

allSolutionDT <- data.table(files = allSolutions)

allSolutionDT[,`:=`(networks = map(files, ~{ load(paste0("./results/",.x))
                                               Solution } )), by = files]


allSolutionDT[,`:=`(APSPpresolveMethod =  str_extract(files, "APSPInteractome|etxInteractome"),
                    seedSet = str_match(files, "steinerTreeSolver_(.*?)_")%>% .[1,2],
                    solver = str_extract(files, "cplexAPI|rcbc|Rglpk")), by = files]


allSolutionDT[,APSPpresolveMethod := ifelse(APSPpresolveMethod == "APSPInteractome", "APSPpresolveMethod", "classicPresolveMethod")]


allSolutionDT[,`:=`(eigenCentralityVector = map(networks, ~{ eigen_centrality(.x)$vector  } )), by = files]
```

```{r}
ScatterPlot <- function(dt,x,y){ 
                
                dt1 <- dt[,.(x = get(x), y = get(y)), by = eval(colnames(dt))]
  
                return(ggplot(dt1, aes(x=x, y=y)) +
    
                ggplot2::geom_point(shape=16, show.legend = FALSE,  alpha = 0.5, color = "paleturquoise4", size = 3) +

                ggplot2::geom_abline(intercept = 0, slope = 1, col="darkred") +
                theme_minimal())}

```

```{r}
eigenCentralityDT <- allSolutionDT[,.(eigenCentrality = unlist(eigenCentralityVector),
                 nodeID = names(unlist(eigenCentralityVector))), by = .(seedSet, solver, APSPpresolveMethod)]


eigenCentralityDT <- dcast(eigenCentralityDT,  nodeID+seedSet+solver~APSPpresolveMethod, value.var = "eigenCentrality", fill = 0) 



ScatterPlot(dt = eigenCentralityDT, x = "APSPpresolveMethod", y = "classicPresolveMethod") +
  facet_wrap(~solver+seedSet, ncol = 5)+
  labs(y = "APSP presolve Method TRUE", x = "APSP presolve Method FALSE", title = "eigen_centrality") +
  theme_minimal(base_size = 20) 

ggsave("./results/EigenCentralityAPSPpresolveMethod_SteinerTree.png", width = 20, height = 12)





```

```{r}

 
allSolutionDT[,`:=`(vcount = map_int(networks, ~{ vcount(.x) } ),
                    isConnected = map_lgl(networks, ~{ is.connected(.x) } ),
                    seeds = seedSetlist[names(seedSetlist) == seedSet]), by = files]


allSolutionDT[,`:=`(containsAllSeeds = map2_lgl(networks, seeds, function(x, y){ y[Accession %in% V(x)$name]$Accession %>% length(.) == nrow(y) } 
                                            
                                            )), by = files]


allSolutionDT[,.(solver, seedSet, vcount, APSPpresolveMethod = ifelse(APSPpresolveMethod == "APSPpresolveMethod", TRUE, FALSE), isConnected, containsAllSeeds)] %>% .[order(APSPpresolveMethod, seedSet)]

allSolutionDT[isConnected == FALSE]$networks[[1]] %>% decompose(.) %>% .[order(map_int(., vcount), decreasing = TRUE)]


```



















